#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Skitgubbe game: second Cloudflare Pages project"

# ── Stage 1: create the project ───────────────────────────────────────────
stage "Create the Pages project"
say "The game gets its own Pages project, separate from the rules page, so a"
say "broken game build can never take skitgubbe.nu down. (ADR 0001.)"
printf '\n'
warn "Do NOT touch the existing 'skitgubbe' project. This creates a new one."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "Choose the 'Pages' tab, then 'Connect to Git'."
step "Pick the repository: rsargeus/skitgubbe"
step "Production branch: master"
printf '\n'
say "Under 'Build settings', set exactly these three fields:"
step "Framework preset:  None"
step "Build command:     npm run build"
step "Build output dir:  dist"
printf '\n'
say "Then expand 'Root directory (advanced)' and set:"
step "Root directory:    game"
printf '\n'
warn "Root directory is the field everything depends on. Without it Cloudflare"
warn "builds from the repo root, finds no package.json, and you get an empty copy"
warn "of the rules page instead of the game."
printf '\n'
step "Give the project a name. 'skitgubbe-game' is suggested."
ask PAGES_PROJECT "Project name you chose:"
PAGES_PROJECT="${PAGES_PROJECT:-skitgubbe-game}"
step "Click 'Save and Deploy'."
pause "Done? Press Enter once the first build has been kicked off."

# ── Stage 2: verify the build ─────────────────────────────────────────────
stage "Verify the first build"
say "Cloudflare is now running 'npm run build' inside game/."
printf '\n'
note "If game/ does not exist yet (issue #1 not implemented), this build will"
note "fail. That is expected — finish issue #1, push, and the project rebuilds."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/${PAGES_PROJECT}"
step "Watch the deployment log until it finishes."
step "Green? Open the *.pages.dev URL it gives you and check the game loads."
printf '\n'
if confirm "Did the build succeed?"; then
  say "Good. On to the custom domain."
else
  warn "Fix the build before continuing: the custom domain will serve whatever"
  warn "the last successful deployment produced, which may be nothing at all."
  if ! confirm "Continue anyway?"; then
    SKIPPED+=("custom domain game.skitgubbe.nu (build was not green)")
    finish
    exit 0
  fi
fi

# ── Stage 3: custom domain ────────────────────────────────────────────────
stage "Point game.skitgubbe.nu at the project"
say "skitgubbe.nu already uses Cloudflare nameservers, so adding the domain here"
say "creates the DNS record for you. There is no separate DNS step."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/${PAGES_PROJECT}/domains"
step "Click 'Set up a custom domain'."
step "Enter: game.skitgubbe.nu"
step "Confirm. Cloudflare adds the CNAME and issues a certificate."
printf '\n'
note "The certificate usually takes under a minute, occasionally a few."
pause "Press Enter once the domain shows as Active."

# ── Stage 4: verify both sites ────────────────────────────────────────────
stage "Verify both sites"
say "Checking that the game is up and the rules page is untouched."
printf '\n'
game_status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 https://game.skitgubbe.nu || echo "000")
rules_status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 https://skitgubbe.nu || echo "000")
ask_status=$(curl -s -o /dev/null -w '%{http_code}' --max-time 45 -X POST https://skitgubbe.nu/ask \
  -H 'Content-Type: application/json' -d '{"question":"test"}' || echo "000")

printf '  game.skitgubbe.nu   %s\n' "$game_status"
printf '  skitgubbe.nu        %s\n' "$rules_status"
printf '  skitgubbe.nu/ask    %s\n' "$ask_status"
printf '\n'

if [[ "$game_status" == "200" ]]; then
  say "${GREEN}✓${RESET} The game is live."
else
  warn "game.skitgubbe.nu returned $game_status. DNS may still be propagating;"
  warn "wait a minute and re-run this stage."
  SKIPPED+=("verify game.skitgubbe.nu (returned $game_status)")
fi

if [[ "$rules_status" == "200" && "$ask_status" == "200" ]]; then
  say "${GREEN}✓${RESET} The rules page and its AI endpoint are unaffected."
else
  warn "The rules page or /ask is not healthy (${rules_status} / ${ask_status})."
  warn "That should not happen — the projects are independent. Investigate before"
  warn "going further."
  SKIPPED+=("rules page health check (${rules_status} / ${ask_status})")
fi

finish
